version: '2'

services:
  geokrety-static:
    image: jrelva/nginx-autoindex:latest
    ports:
     - 8002:80
    volumes:
      - ./content:/usr/share/nginx/html
      - ../GEOKRETY-LEGACY-PROD/vars/obrazki:/usr/share/nginx/html/images/obrazki:ro
      - ../GEOKRETY-LEGACY-PROD/vars/obrazki-male:/usr/share/nginx/html/images/obrazki-male:ro
      - ../GEOKRETY-LEGACY-PROD/vars/statpics:/usr/share/nginx/html/images/statpics:ro
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:cdn.geokrety.org,cdn.geokrety.kumy.org"
      - "traefik.docker.network=srv_geokrety-front"
#     networks:
#       - front
#
# networks:
#   front:
#     external:
#       name: srv_geokrety-front
